---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gups.fullname" $ }}-secrets
  labels:
    app: {{ template "gups.name" . }}
    chart: {{ template "gups.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value.value | b64enc }}
{{- end }}
